export const data = [
  {
    title: "I'm your man",
    category: "Romance",
    id: "qlkimlk",
    rate: 8,
    cover:
      "https://www.hautetcourt.com/wp-content/uploads/2021/06/120-man-scaled.jpg",
    cast: "Dominic Purcell, Kais Setti, Graham McTavish",
    release: "2012-12-25",
    trailerSrc: "https://www.youtube.com/embed/ARxpqS9DQyA",
  },
  {
    title: "Blood Red Sky",
    category: "Horror",
    id: "ghtyredd",
    rate: 6,
    cover: "https://horrorzone.ru/uploads/_gallery2/103274/blood-red-sky00.png",
    cast: "Dan Stevens, Mareen Eggert, Sandra Holler",
    release: "2021-06-17",
    trailerSrc: "https://www.youtube.com/embed/ySFBYrAdTtI",
  },

  {
    title: "Athena",
    category: "Action",
    id: "fvcretyus",
    rate: 9,
    cover:
      "https://images.squarespace-cdn.com/content/v1/5033fa18c4aacd0a249de051/1664583931111-QMS7NZBALND8LM90KT38/mon-athena-ray-taylor-show.png?format=1500w",
    cast: "Dali Bensala7, Ouassini Mbarek, Karim Lasmi",
    release: "2022-09-02",
    trailerSrc: "https://www.youtube.com/embed/vRunUkdkK8s",
  },

  {
    title: "Night Run",
    category: "Drame",
    id: "vbnchyetr",
    rate: 10,
    cover:
      "https://www.cine-feuilles.ch/storage/app/uploads/public/5a3/e7c/221/5a3e7c22150f1174687681.jpg",
    cast: "Liam Neeson, Joel Kinnaman, Body Holbrook",
    release: "2015-03-09",
    trailerSrc: "https://www.youtube.com/embed/7uDuFh-nC-c",
  },
  {
    title: "The Age Of Adaline",
    category: "Love",
    id: "anhjuiopt",
    rate: 5,
    cover:
      "https://m.media-amazon.com/images/M/MV5BMTAzMTQzMTA2MjheQTJeQWpwZ15BbWU4MDk2MTg2MzUx._V1_.jpg",
    cast: "Liam Neeson, Joel Kinnaman, Body Holbrook",
    release: "2015-03-09",
    trailerSrc: "https://www.youtube.com/embed/g9-SnMldtGY",
  },
  {
    title: "Dilwale",
    category: "Love",
    id: "mplkjarez",
    rate: 5,
    cover: "https://fr.web.img5.acsta.net/pictures/15/11/13/17/11/538881.jpg",
    cast: "Kajol Meera, Varun Dhawan, Chetna Pand",
    release: "2017-03-09",
    trailerSrc: "https://www.youtube.com/embed/rg_aGcIl4qk",
  },
  {
    title: "The Prom",
    category: "Comedy",
    id: "bvytloiuu",
    rate: 7,
    cover: "https://fr.web.img2.acsta.net/pictures/20/11/27/10/29/0452712.jpg",
    cast: "Jo Ellen, Ariana DeBose, Andrew Rannells",
    release: "2020-09-02",
    trailerSrc: "https://www.youtube.com/embed/Zt9v3f35l5Y",
  },
  {
    title: "Loin de périf",
    category: "Comedy",
    id: "lmpvcbnryts",
    rate: 9,
    cover: "https://fr.web.img3.acsta.net/pictures/22/05/05/14/30/4993969.jpg",
    cast: "Omar Sy, Lorent Lafitte, Flavie Péan",
    release: "2022-05-06",
    trailerSrc: "https://www.youtube.com/embed/pLfCg85DwEY",
  },
];
